# This file is @generated, regenerate by re-running test with `-- --env BUCK2_UPDATE_GOLDEN=1` appended to the test command

{
  "failures": {
    "root//fail_action:fail_error_handler_output_not_written": "Action failed: root//fail_action:fail_error_handler_output_not_written (<unspecified>) (fail_error_handler_output_not_written)\nLocal command returned non-zero exit code 1\nLocal command: env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/<HASH>/fail_error_handler_output_not_written' python3 fail_action/fail_compile.py buck-out/v2/gen/root/<HASH>/fail_action/__fail_error_handler_output_not_written__/output\nStdout: <empty>\nStderr:\n  File \"fail_action/fail_compile.py\", line 9\n    does not compile\n             ^\nSyntaxError: invalid syntax\n\nCould not produce error diagnostics:\nOutput 'buck-out/v2/gen/root/<HASH>/fail_action/__fail_error_handler_output_not_written__/output' defined for error handler does not exist. This is likely due to file not being created, please ensure the action would produce an output\n"
  },
  "results": {
    "root//fail_action:fail_error_handler_output_not_written": {
      "configured": {
        "<unspecified>": {
          "configured_graph_size": null,
          "errors": [
            {
              "action_error": {
                "digest": "<DIGEST>",
                "error_content": "<STRING_HASH>",
                "error_diagnostics": {
                  "handler_invocation_error": "<STRING_HASH>"
                },
                "key": {
                  "owner": "root//fail_action:fail_error_handler_output_not_written (<unspecified>)"
                },
                "name": {
                  "category": "fail_error_handler_output_not_written",
                  "identifier": ""
                },
                "stderr_content": "<STRING_HASH>",
                "stdout_content": "<STRING_HASH>"
              },
              "cause_index": 0,
              "error_tags": [
                "ACTION_COMMAND_FAILURE",
                "ANY_ACTION_EXECUTION"
              ],
              "message_content": "<STRING_HASH>"
            }
          ],
          "other_outputs": {},
          "outputs": {},
          "success": "FAIL"
        }
      },
      "configured_graph_size": null,
      "errors": [],
      "other_outputs": {},
      "outputs": {},
      "success": "FAIL"
    }
  },
  "strings": {
    "<STRING_HASH>": "",
    "<STRING_HASH>": "  File \"fail_action/fail_compile.py\", line 9\n    does not compile\n             ^\nSyntaxError: invalid syntax\n",
    "<STRING_HASH>": "Action failed: root//fail_action:fail_error_handler_output_not_written (<unspecified>) (fail_error_handler_output_not_written)\nLocal command returned non-zero exit code 1\nLocal command: env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/<HASH>/fail_error_handler_output_not_written' python3 fail_action/fail_compile.py buck-out/v2/gen/root/<HASH>/fail_action/__fail_error_handler_output_not_written__/output\nStdout: <empty>\nStderr:\n  File \"fail_action/fail_compile.py\", line 9\n    does not compile\n             ^\nSyntaxError: invalid syntax\n\nCould not produce error diagnostics:\nOutput 'buck-out/v2/gen/root/<HASH>/fail_action/__fail_error_handler_output_not_written__/output' defined for error handler does not exist. This is likely due to file not being created, please ensure the action would produce an output\n",
    "<STRING_HASH>": "Local command returned non-zero exit code 1",
    "<STRING_HASH>": "Output 'buck-out/v2/gen/root/<HASH>/fail_action/__fail_error_handler_output_not_written__/output' defined for error handler does not exist. This is likely due to file not being created, please ensure the action would produce an output"
  },
  "success": false,
  "truncated": false
}
