# This file is @generated, regenerate by re-running test with `-- --env BUCK2_UPDATE_GOLDEN=1` appended to the test command

{
  "failures": {
    "root//fail_action:fail_one": "Action failed: root//fail_action:fail_one (root//config:dog_platform#<HASH>) (failname)\nRemote command returned non-zero exit code 1\nRemote action, reproduce with: `frecli cas download-action <DIGEST>`\nStdout: <empty>\nStderr: <empty>\n",
    "root//fail_analysis:fail_analysis": "Error running analysis for `root//fail_analysis:fail_analysis (<unspecified>)`\n\nCaused by:\n    Traceback (most recent call last):\n      File <builtin>, in <module>\n      * fail_analysis/fail_analysis.bzl:9, in _impl\n          fail(\"Failure during analysis\")\n    error: fail: Failure during analysis\n     --> fail_analysis/fail_analysis.bzl:9:5\n      |\n    9 |     fail(\"Failure during analysis\")\n      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      |\n    "
  },
  "results": {
    "root//fail_action:fail_one": {
      "configured": {
        "root//config:dog_platform#<HASH>": {
          "configured_graph_size": null,
          "errors": [
            {
              "action_error": {
                "digest": "<DIGEST>",
                "error_content": "<STRING_HASH>",
                "error_diagnostics": null,
                "key": {
                  "owner": "root//fail_action:fail_one (root//config:dog_platform#<HASH>)"
                },
                "name": {
                  "category": "failname",
                  "identifier": ""
                },
                "stderr_content": "<STRING_HASH>",
                "stdout_content": "<STRING_HASH>"
              },
              "cause_index": 0,
              "error_tags": [
                "ACTION_COMMAND_FAILURE",
                "ANY_ACTION_EXECUTION"
              ],
              "message_content": "<STRING_HASH>"
            }
          ],
          "other_outputs": {},
          "outputs": {},
          "success": "FAIL"
        }
      },
      "configured_graph_size": null,
      "errors": [],
      "other_outputs": {},
      "outputs": {},
      "success": "FAIL"
    },
    "root//fail_analysis:fail_analysis": {
      "configured": {
        "<unspecified>": {
          "configured_graph_size": null,
          "errors": [
            {
              "action_error": null,
              "cause_index": 1,
              "error_tags": [
                "ANALYSIS",
                "STARLARK_FAIL"
              ],
              "message_content": "<STRING_HASH>"
            }
          ],
          "other_outputs": {},
          "outputs": {},
          "success": "FAIL"
        }
      },
      "configured_graph_size": null,
      "errors": [],
      "other_outputs": {},
      "outputs": {},
      "success": "FAIL"
    }
  },
  "strings": {
    "<STRING_HASH>": "",
    "<STRING_HASH>": "Action failed: root//fail_action:fail_one (root//config:dog_platform#<HASH>) (failname)\nRemote command returned non-zero exit code 1\nRemote action, reproduce with: `frecli cas download-action <DIGEST>`\nStdout: <empty>\nStderr: <empty>\n",
    "<STRING_HASH>": "Error running analysis for `root//fail_analysis:fail_analysis (<unspecified>)`\n\nCaused by:\n    Traceback (most recent call last):\n      File <builtin>, in <module>\n      * fail_analysis/fail_analysis.bzl:9, in _impl\n          fail(\"Failure during analysis\")\n    error: fail: Failure during analysis\n     --> fail_analysis/fail_analysis.bzl:9:5\n      |\n    9 |     fail(\"Failure during analysis\")\n      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      |\n    ",
    "<STRING_HASH>": "Remote command returned non-zero exit code 1"
  },
  "success": false,
  "truncated": false
}
